DefaultContentLanguage = "en"
baseURL = "https://www.product.ceo"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
summarylength = 20
theme = "anatole"
title = "Product CEO"

[[menu.main]]
identifier = "ExecutiveLibrary"
url = "/ExecutiveLibrary"
name = "Executive Library"
weight = 1
[[menu.main]]
identifier = "ExecutiveSummary"
url = "/ExecutiveSummary"
name = "Executive Summary"
weight = 2
[[menu.main]]
identifier = "FirstParty"
url = "/FirstParty"
name = "First Party"
weight = 3

[params]
author = "Product CEO"
description = "Microsoft PM || Stanford CS"
doNotLoadAnimations = false
favicon = "favicons/"
keywords = ""
mainSections = ["ExecutiveLibrary"]
profilePicture = "profile/junwon.jpg"
title = "Junwon Park"

[params.math]
enable = false
use = "katex"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/productceo/"
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/microsoftpm/"
[[params.socialIcons]]
icon = "fab fa-reddit-alien"
title = "Reddit"
url = "https://www.reddit.com/productceo/"
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/productceo/"
[[params.socialIcons]]
icon = "fas fa-podcast"
title = "Podcast"
url = "https://anchor.fm/productceo/"
