DefaultContentLanguage = "en"
baseURL = "https://www.product.ceo"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
summarylength = 20
theme = "anatole"
title = "Product CEO"

[params.math]
enable = false
use = "katex"

[taxonomies]

[[menu.main]]
identifier = "Executive Library"
url = "/Executive Library"
name = "Executive Library"
weight = 1
[[menu.main]]
identifier = "Executive Summary"
url = "/Executive Summary"
name = "Executive Summary"
weight = 2
[[menu.main]]
identifier = "First Party"
url = "/First Party"
name = "First Party"
weight = 3

[params]
author = "Product CEO"
description = "Microsoft PM || Stanford CS"
doNotLoadAnimations = false
favicon = "favicons/"
keywords = ""
mainSections = ["ExecutiveLibrary"]
mainSection1 = ["ExecutiveLibrary"]
mainSection2 = ["ExecutiveSummary"]
mainSection3 = ["FirstParty"]
profilePicture = "profile/junwon.png"
name = "Junwon Park"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/productceo/"
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/microsoftpm/"
[[params.socialIcons]]
icon = "fab fa-reddit-alien"
title = "Reddit"
url = "https://www.reddit.com/productceo/"
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/productceo/"
[[params.socialIcons]]
icon = "fas fa-podcast"
title = "Podcast"
url = "https://anchor.fm/productceo/"
